#!/bin/bash

sudo cp -r scripts/* /usr/local/bin/

sudo cp sddm/sddm.conf /etc/sddm.conf.d/
sudo tar -xzvf sddm/sugar-dark.tar -C /usr/share/sddm/themes/
sudo cp sddm/theme.conf /usr/share/sddm/themes/sugar-dark/
sudo cp sddm/Background.jpg /usr/share/sddm/themes/sugar-dark/

cp .bashrc ~
cp .bash_profile ~
cp .zshrc ~
cp .vimrc ~
cp ascii/* ~

cp -r .themes ~
cp -r .icons ~
cp -r .fonts ~
cp -r .ssh ~
cp -r .config ~

unzip -qo ~/.themes/dracula.zip -d ~/.themes/
unzip -qo ~/.icons/dracula.zip -d ~/.icons/
unzip -qo ~/.fonts/hack.zip -d ~/.fonts/

sudo tee -a /etc/environment <<< "export QT_QPA_PLATFORMTHEME=qt5ct"
