#!/bin/bash

sudo cp -r scripts/* /usr/local/bin/
sudo cp sddm.conf /etc/sddm.conf.d/
sudo cp -r sugar-dark /usr/share/sddm/themes/

cp .bashrc ~
cp .bash_profile ~
cp .zshrc ~
cp .vimrc ~
cp ascii/* ~

cp -r .themes ~
cp -r .icons ~
cp -r .fonts ~
cp -r .ssh ~

cp -r .config/* ~/.config/

unzip -qo ~/.themes/dracula.zip -d ~/.themes/
unzip -qo ~/.icons/dracula.zip -d ~/.icons/
unzip -qo ~/.fonts/hack.zip -d ~/.fonts/

sudo tee -a /etc/environment <<< "export QT_QPA_PLATFORMTHEME=qt5ct"
