-- local status, plugin = pcall(require,'telescope.builtin')
-- if not status then
--     print('Error with plugin: ', plugin)
-- else
--
-- vim.keymap.set('n', '<leader>f', plugin.find_files, {})
-- vim.keymap.set('n', '<leader>gf', plugin.git_files, {})
-- end
